  
name: deploy-master
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update qy
        run: sudo apt-get update -qq
      - name: Installing lftp
        run: sudo apt-get install -y -qq lftp

      - name: Send build To Over lftp
        run: lftp -c "set ftp:ssl-allow no; open -u epiz_26397561,r7ehK1nHPE ftpsite.com; mirror -v ./README.md /htdocs --reverse --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"