  
name: deploy-master
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update qy
        run: sudo apt-get update -qy
      - name: Installing lftp
        run: apt-get install -y lftp
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command

      - name: Config Assets For Surge
        run: sudo mv ./build/index.html ./build/200.html

      - name: Installing Surge
        run: sudo npm install -g surge

      - name: Deploying website
        run: surge --project ./build/ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

      - run: echo "Please visit => ${{ secrets.SURGE_DOMAIN }}"